version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    container_name: v2fly-core
    network_mode: host
    volumes:
      - /etc/v2ray/config.json:/etc/v2ray/config.json

